
spring:
  #mysql configuration
  datasource:
    url: jdbc:mysql://localhost:3306/moneymanager
    username: root
    password: root
  #JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# prefix of endpoints
server:
  servlet:
    context-path: /api/v1.0



